version: 2.1
jobs:
  Branches-Filtered:
    docker:
      - image: circleci/node:10.16.3
      - image: mongo:4.2.0
    steps:
      - checkout
      - run:
          name: build-filter
          command: echo "This branch will be tested"

  Run-Hello:
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python hello.py

  Test-Hello:
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python test_hello.py

  Now-Complete:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Approval Complete
          command: |
            echo 'Tests complete.'
workflows:
  version: 2
  Working-Workflow:
    jobs:
      - Branches-Filtered:
          filters:
            branches:
              ignore:

      - Run-Hello

      - Test-Hello:
          requires:
            - Run-Hello


      - Now-Complete:
          requires:
            - Branches-Filtered
